Repository fusioninventory/fusioninventory-agent, pull requests merged in 2019-12, with the labels that each got.

#747 fix: use XML::XPath to parse XML
  lib/FusionInventory/Agent/Task/Inventory/Win32/Softwares.pm
Labels: Inventory-task, win32

#753 Added Eaton ePDU support
  lib/FusionInventory/Agent/SNMP/MibSupport/EatonEpdu.pm
  share/sysobject.ids
Labels: NetDiscovery-task, NetInventory-task

#749 fix: also use static values for vlan detection
  lib/FusionInventory/Agent/Tools/Hardware.pm
Labels: NetInventory-task
